name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  

          user: Robeco945
          commits_authoring: Robeco945, your-email@example.com
          repositories_affiliations: owner, collaborator, organization_member
          template: classic
          base: "header, activity, repositories"
          base_indepth: yes            
          config_timezone: Europe/Helsinki
          
          plugin_languages: yes
          #plugin_languages_ignored: html, css  
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes        
          plugin_languages_analysis_timeout: 15 # Increase to 15 mins
          plugin_languages_analysis_timeout_repositories: 3 # Allow more time per repo
